#!/bin/sh

xargs -t coffee -j ../script/main.js -w -c << EOF
_utils.coffee
gfx.coffee
keys.coffee
levels/Level.coffee
levels/levels.coffee
entities/_Entity.coffee
entities/Player.coffee
entities/Ninja.coffee
blocks/_Block.coffee
blocks/Dirt.coffee
blocks/Rock.coffee
blocks/Treasure.coffee
blocks/Ladder.coffee
blocks/Gravel.coffee
game.coffee
EOF
